# -*- coding: utf-8 -*-
"""
ScholarSearch dataset
----------------------
A curated set of real, publicly known Indian scholarship and welfare scheme
programmes (central government, state government, and major private
foundations). Descriptions are written independently in our own words for
this project.

IMPORTANT (for the report's Dataset Description section):
Eligibility figures (income caps, percentages, benefit amounts) are commonly
cited approximate figures and CHANGE periodically via government notification.
This dataset is a representative snapshot for demonstrating the retrieval
system, not a live feed. A production deployment would sync nightly from
the National Scholarship Portal (scholarships.gov.in) and state portals via
the fetch_live.py scraper stub included in this project.
"""

SCHEMES = [
    # ---------------- CENTRAL GOVERNMENT ----------------
    {
        "name": "National Means-cum-Merit Scholarship (NMMS)",
        "provider": "Ministry of Education, Govt. of India",
        "level": "School (Class 9-12)",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": 350000,
        "min_percentage": 55,
        "benefit_amount": "Rs. 12,000 per year",
        "description": "A central scheme to prevent dropout at the secondary stage by supporting meritorious students from economically weaker sections studying in government, government-aided, and local body schools.",
        "tags": "school merit dropout secondary economically weaker",
        "url": "https://scholarships.gov.in",
    },
    {
        "name": "Central Sector Scheme of Scholarships for College and University Students",
        "provider": "Ministry of Education, Govt. of India",
        "level": "UG",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": 450000,
        "min_percentage": 80,
        "benefit_amount": "Rs. 10,000 - 20,000 per year",
        "description": "Awarded to top-performing Class 12 students who go on to pursue regular undergraduate degree courses, to help meet living and academic expenses.",
        "tags": "undergraduate merit top rank class 12",
        "url": "https://scholarships.gov.in",
    },
    {
        "name": "AICTE Pragati Scholarship for Girls",
        "provider": "AICTE",
        "level": "Diploma/UG",
        "category": "General",
        "gender": "Female",
        "state": "All India",
        "max_income": 800000,
        "min_percentage": None,
        "benefit_amount": "Rs. 50,000 per year",
        "description": "Supports girl students admitted to AICTE-approved technical diploma and degree programmes, with preference for one girl per family, to reduce gender gap in technical education.",
        "tags": "girls technical engineering diploma AICTE women",
        "url": "https://www.aicte-india.org/schemes/students-development-schemes",
    },
    {
        "name": "AICTE Saksham Scholarship for Specially-Abled Students",
        "provider": "AICTE",
        "level": "Diploma/UG",
        "category": "PWD",
        "gender": "Any",
        "state": "All India",
        "max_income": 800000,
        "min_percentage": None,
        "benefit_amount": "Rs. 50,000 per year",
        "description": "Financial assistance for students with more than 40% disability pursuing technical diploma or degree courses at AICTE-approved institutions.",
        "tags": "disability specially abled technical engineering diploma PWD",
        "url": "https://www.aicte-india.org/schemes/students-development-schemes",
    },
    {
        "name": "Post Matric Scholarship for SC Students",
        "provider": "Ministry of Social Justice and Empowerment",
        "level": "Post-Matric/UG/PG",
        "category": "SC",
        "gender": "Any",
        "state": "All India",
        "max_income": 250000,
        "min_percentage": None,
        "benefit_amount": "Tuition fee + maintenance allowance",
        "description": "Covers tuition fees, maintenance allowance, and other essential expenses for Scheduled Caste students pursuing studies beyond matriculation.",
        "tags": "scheduled caste SC reservation post matric tuition",
        "url": "https://scholarships.gov.in",
    },
    {
        "name": "Post Matric Scholarship for OBC Students",
        "provider": "Ministry of Social Justice and Empowerment",
        "level": "Post-Matric/UG/PG",
        "category": "OBC",
        "gender": "Any",
        "state": "All India",
        "max_income": 150000,
        "min_percentage": None,
        "benefit_amount": "Tuition fee + maintenance allowance",
        "description": "Financial support for Other Backward Class students studying beyond the matriculation level, covering course fees and a monthly maintenance allowance.",
        "tags": "OBC other backward class post matric tuition reservation",
        "url": "https://scholarships.gov.in",
    },
    {
        "name": "Post Matric Scholarship for ST Students",
        "provider": "Ministry of Tribal Affairs",
        "level": "Post-Matric/UG/PG",
        "category": "ST",
        "gender": "Any",
        "state": "All India",
        "max_income": 250000,
        "min_percentage": None,
        "benefit_amount": "Tuition fee + maintenance allowance",
        "description": "Supports Scheduled Tribe students pursuing education beyond matriculation with fee reimbursement and a monthly maintenance grant.",
        "tags": "scheduled tribe ST tribal post matric reservation",
        "url": "https://scholarships.gov.in",
    },
    {
        "name": "Pre Matric Scholarship for Minorities",
        "provider": "Ministry of Minority Affairs",
        "level": "School (Class 1-10)",
        "category": "Minority",
        "gender": "Any",
        "state": "All India",
        "max_income": 100000,
        "min_percentage": 50,
        "benefit_amount": "Rs. 1,000 - 7,000 per year",
        "description": "Assists school-going children from notified minority communities (Muslim, Christian, Sikh, Buddhist, Jain, Parsi) with fees and essential school supplies.",
        "tags": "minority pre matric school children fees",
        "url": "https://scholarships.gov.in",
    },
    {
        "name": "Post Matric Scholarship for Minorities",
        "provider": "Ministry of Minority Affairs",
        "level": "Post-Matric/UG/PG",
        "category": "Minority",
        "gender": "Any",
        "state": "All India",
        "max_income": 200000,
        "min_percentage": 50,
        "benefit_amount": "Tuition fee + maintenance allowance",
        "description": "Financial aid for minority community students studying in Class 11 and above, including professional and technical courses.",
        "tags": "minority post matric professional technical fees",
        "url": "https://scholarships.gov.in",
    },
    {
        "name": "Merit-cum-Means Scholarship for Minorities",
        "provider": "Ministry of Minority Affairs",
        "level": "UG/PG/Professional",
        "category": "Minority",
        "gender": "Any",
        "state": "All India",
        "max_income": 250000,
        "min_percentage": 50,
        "benefit_amount": "Tuition fee + maintenance allowance",
        "description": "Targeted at minority students enrolled in technical and professional degree/diploma courses who demonstrate both academic merit and financial need.",
        "tags": "minority merit means professional technical degree",
        "url": "https://scholarships.gov.in",
    },
    {
        "name": "Begum Hazrat Mahal National Scholarship",
        "provider": "Maulana Azad Education Foundation",
        "level": "School (Class 9-12)",
        "category": "Minority",
        "gender": "Female",
        "state": "All India",
        "max_income": 200000,
        "min_percentage": None,
        "benefit_amount": "Rs. 5,000 - 6,000 per year",
        "description": "A scheme exclusively for girls from minority communities studying in Classes 9 to 12, aimed at reducing dropout among minority girl students.",
        "tags": "minority girls women school dropout Class 9 to 12",
        "url": "https://scholarships.gov.in",
    },
    {
        "name": "PM YASASVI Scholarship (OBC / EBC / DNT)",
        "provider": "Ministry of Social Justice and Empowerment",
        "level": "School/UG",
        "category": "OBC",
        "gender": "Any",
        "state": "All India",
        "max_income": 250000,
        "min_percentage": None,
        "benefit_amount": "Rs. 75,000 - 1,25,000 per year (top class), lower for pre/post matric",
        "description": "An umbrella scheme covering pre-matric, post-matric, and top-class education support for students from Other Backward Classes, Economically Backward Classes, and De-notified Tribes.",
        "tags": "OBC EBC denotified tribes YASASVI merit top class",
        "url": "https://yet.nta.ac.in",
    },
    {
        "name": "Top Class Education Scheme for SC Students",
        "provider": "Ministry of Social Justice and Empowerment",
        "level": "UG/PG",
        "category": "SC",
        "gender": "Any",
        "state": "All India",
        "max_income": 800000,
        "min_percentage": None,
        "benefit_amount": "Full tuition fee + living expenses at notified top institutions",
        "description": "Covers the full cost of education for Scheduled Caste students admitted to a notified list of top-ranked institutions such as IITs, IIMs, NLUs, and central universities.",
        "tags": "scheduled caste SC top institutions IIT IIM full fee",
        "url": "https://scholarships.gov.in",
    },
    {
        "name": "National Fellowship for OBC Students",
        "provider": "Ministry of Social Justice and Empowerment",
        "level": "PhD",
        "category": "OBC",
        "gender": "Any",
        "state": "All India",
        "max_income": 600000,
        "min_percentage": None,
        "benefit_amount": "Monthly fellowship on UGC-NET pattern",
        "description": "A doctoral fellowship supporting OBC candidates pursuing M.Phil or PhD research in universities and research institutions recognised by UGC.",
        "tags": "OBC PhD fellowship research doctoral UGC NET",
        "url": "https://scholarships.gov.in",
    },
    {
        "name": "National Overseas Scholarship for SC/ST/PWD Students",
        "provider": "Ministry of Social Justice and Empowerment",
        "level": "Study Abroad (Masters/PhD)",
        "category": "SC/ST/PWD",
        "gender": "Any",
        "state": "All India",
        "max_income": 800000,
        "min_percentage": None,
        "benefit_amount": "Tuition, living allowance, and airfare for study abroad",
        "description": "Funds Scheduled Caste, Scheduled Tribe, and PWD candidates pursuing postgraduate or doctoral study at recognised foreign universities in notified priority fields.",
        "tags": "study abroad SC ST PWD overseas masters PhD international",
        "url": "https://scholarships.gov.in",
    },
    {
        "name": "Ishan Uday Scholarship for North Eastern Region Students",
        "provider": "Ministry of Education",
        "level": "UG",
        "category": "General",
        "gender": "Any",
        "state": "North-Eastern States",
        "max_income": 450000,
        "min_percentage": None,
        "benefit_amount": "Up to Rs. 5,400 per month",
        "description": "Supports undergraduate students from the eight North Eastern states studying anywhere in India, aimed at improving access to higher education for the region.",
        "tags": "north east NER undergraduate regional",
        "url": "https://scholarships.gov.in",
    },
    {
        "name": "National Fellowship for Students with Disabilities",
        "provider": "Department of Empowerment of Persons with Disabilities",
        "level": "M.Phil/PhD",
        "category": "PWD",
        "gender": "Any",
        "state": "All India",
        "max_income": None,
        "min_percentage": None,
        "benefit_amount": "Monthly fellowship on UGC-NET pattern + contingency grant",
        "description": "A research fellowship for candidates with 40% or more disability pursuing M.Phil or PhD programmes, with additional allowances for escorts and equipment.",
        "tags": "disability PWD fellowship PhD research MPhil",
        "url": "https://scholarships.gov.in",
    },
    {
        "name": "CBSE Udaan Scheme for Girls",
        "provider": "CBSE",
        "level": "School (Class 11-12)",
        "category": "General",
        "gender": "Female",
        "state": "All India",
        "max_income": 600000,
        "min_percentage": 70,
        "benefit_amount": "Free study material and online mentoring for engineering entrance prep",
        "description": "A non-monetary scheme providing free e-learning resources and mentorship to Class 11 and 12 girl students to help bridge the gender gap in engineering entrance exams.",
        "tags": "girls engineering entrance JEE preparation mentoring",
        "url": "https://cbseacademic.nic.in/udaan.html",
    },
    {
        "name": "INSPIRE Scholarship for Higher Education (SHE)",
        "provider": "Department of Science and Technology",
        "level": "UG/PG (Science)",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": None,
        "min_percentage": None,
        "benefit_amount": "Rs. 80,000 per year",
        "description": "Rewards top-rank students who choose to pursue a natural or basic science degree at the undergraduate and postgraduate level, encouraging research careers in science.",
        "tags": "science research basic sciences INSPIRE top rank",
        "url": "https://online-inspire.gov.in",
    },

    # ---------------- MAHARASHTRA STATE SCHEMES ----------------
    {
        "name": "Maharashtra Post-Matric Scholarship (SC/ST/OBC/VJNT/SBC)",
        "provider": "Government of Maharashtra, Social Justice Dept.",
        "level": "Post-Matric/UG/PG",
        "category": "SC",
        "gender": "Any",
        "state": "Maharashtra",
        "max_income": 250000,
        "min_percentage": None,
        "benefit_amount": "Tuition fee + examination fee + maintenance allowance",
        "description": "Maharashtra's state-level scholarship for students from Scheduled Caste, Scheduled Tribe, and other notified backward class categories, covering tuition and hostel expenses within the state.",
        "tags": "maharashtra SC ST OBC VJNT SBC state scholarship tuition",
        "url": "https://mahadbtmahait.gov.in",
    },
    {
        "name": "Rajarshi Chhatrapati Shahu Maharaj Scholarship (EBC)",
        "provider": "Government of Maharashtra",
        "level": "Professional/UG",
        "category": "EWS",
        "gender": "Any",
        "state": "Maharashtra",
        "max_income": 800000,
        "min_percentage": None,
        "benefit_amount": "Full tuition fee waiver at government/aided colleges",
        "description": "Provides full tuition fee concession to economically backward class students from Maharashtra enrolled in professional degree and diploma courses at recognised institutes.",
        "tags": "maharashtra EBC economically backward tuition waiver professional",
        "url": "https://mahadbtmahait.gov.in",
    },
    {
        "name": "Maharashtra EBC (Freeship) Scheme for Professional Courses",
        "provider": "Government of Maharashtra",
        "level": "Diploma/UG/PG",
        "category": "General",
        "gender": "Any",
        "state": "Maharashtra",
        "max_income": 800000,
        "min_percentage": None,
        "benefit_amount": "50% tuition fee waiver",
        "description": "A fee-concession scheme open to Maharashtra domicile students from economically backward families studying in professional and technical institutes within the state.",
        "tags": "maharashtra EBC freeship fee waiver professional technical",
        "url": "https://mahadbtmahait.gov.in",
    },
    {
        "name": "Dr. Panjabrao Deshmukh Hostel Maintenance Allowance",
        "provider": "Government of Maharashtra",
        "level": "UG/PG",
        "category": "OBC",
        "gender": "Any",
        "state": "Maharashtra",
        "max_income": 100000,
        "min_percentage": None,
        "benefit_amount": "Monthly hostel maintenance allowance",
        "description": "Provides a monthly maintenance allowance to OBC students from Maharashtra who stay in a hostel or rented accommodation away from their home taluka to pursue higher education.",
        "tags": "maharashtra OBC hostel maintenance allowance",
        "url": "https://mahadbtmahait.gov.in",
    },
    {
        "name": "Maharashtra Rajarshi Shahu Maharaj Merit Scholarship",
        "provider": "Government of Maharashtra",
        "level": "UG",
        "category": "General",
        "gender": "Any",
        "state": "Maharashtra",
        "max_income": None,
        "min_percentage": 80,
        "benefit_amount": "One-time merit award",
        "description": "Recognises Maharashtra state board toppers at the HSC level who secure admission into recognised degree colleges within the state.",
        "tags": "maharashtra merit HSC topper state board",
        "url": "https://mahadbtmahait.gov.in",
    },

    # ---------------- PRIVATE / CORPORATE FOUNDATIONS ----------------
    {
        "name": "Reliance Foundation Undergraduate Scholarship",
        "provider": "Reliance Foundation",
        "level": "UG",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": 1500000,
        "min_percentage": 60,
        "benefit_amount": "Up to Rs. 2,00,000 over the degree",
        "description": "Supports meritorious first-year undergraduate students across all streams with financial aid, mentoring sessions, and access to an alumni network.",
        "tags": "private undergraduate merit mentoring Reliance",
        "url": "https://www.reliancefoundation.org/scholarships",
    },
    {
        "name": "Aditya Birla Scholarship",
        "provider": "Aditya Birla Group",
        "level": "UG/PG (Engineering, Management, Law)",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": None,
        "min_percentage": None,
        "benefit_amount": "Up to Rs. 1,75,000 per year plus mentorship",
        "description": "A prestigious merit scholarship for students at premier engineering, management, and law institutes, selected through academic performance and a personal interview.",
        "tags": "private merit engineering management law premier institutes",
        "url": "https://www.adityabirlascholars.net",
    },
    {
        "name": "HDFC Bank Parivartan ECS Scholarship",
        "provider": "HDFC Bank",
        "level": "School/UG/PG",
        "category": "EWS",
        "gender": "Any",
        "state": "All India",
        "max_income": 250000,
        "min_percentage": 50,
        "benefit_amount": "Course-fee based, up to full tuition",
        "description": "Offers educational financial aid to meritorious students from economically disadvantaged backgrounds studying in school, undergraduate, or postgraduate courses.",
        "tags": "private EWS economically weaker fee support HDFC",
        "url": "https://www.hdfcbank.com/csr/parivartan",
    },
    {
        "name": "ONGC Scholarship for SC/ST/PWD/Girl Students",
        "provider": "Oil and Natural Gas Corporation",
        "level": "UG (Engineering, Medicine, MBA)",
        "category": "SC/ST/PWD",
        "gender": "Any",
        "state": "All India",
        "max_income": None,
        "min_percentage": 60,
        "benefit_amount": "Rs. 48,000 per year",
        "description": "Corporate social responsibility scholarship for SC, ST, and PWD students, and separately for girl students, pursuing professional degrees in engineering, medicine, or management.",
        "tags": "ONGC SC ST PWD girls engineering medicine MBA corporate",
        "url": "https://www.ongcscholar.org",
    },
    {
        "name": "L'Oreal India For Young Women in Science Scholarship",
        "provider": "L'Oreal India",
        "level": "PG (Science)",
        "category": "General",
        "gender": "Female",
        "state": "All India",
        "max_income": None,
        "min_percentage": None,
        "benefit_amount": "Rs. 2,50,000",
        "description": "Recognises young women pursuing postgraduate research in the physical sciences, mathematics, or engineering, encouraging greater female representation in STEM research.",
        "tags": "women science STEM postgraduate research L'Oreal",
        "url": "https://www.lorealindia.com",
    },
    {
        "name": "Sitaram Jindal Foundation Scholarship",
        "provider": "Sitaram Jindal Foundation",
        "level": "School/UG/PG/Diploma",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": 300000,
        "min_percentage": None,
        "benefit_amount": "Rs. 500 - 3,000 per month depending on course",
        "description": "A broad-based need-and-merit scholarship covering students from Class 11 through postgraduate and vocational courses across most disciplines.",
        "tags": "need merit vocational broad based Jindal",
        "url": "https://sitaramjindalfoundation.org",
    },
    {
        "name": "LIC Golden Jubilee Scholarship",
        "provider": "Life Insurance Corporation of India",
        "level": "School/UG/Professional",
        "category": "EWS",
        "gender": "Any",
        "state": "All India",
        "max_income": 300000,
        "min_percentage": None,
        "benefit_amount": "Rs. 1,000 - 20,000 per year",
        "description": "Provides financial assistance to economically weaker students from Class 11 onward, with higher amounts for students pursuing professional and technical courses.",
        "tags": "LIC EWS professional technical economically weaker",
        "url": "https://licindia.in/golden-jubilee-foundation",
    },
    {
        "name": "Colgate Keep India Smiling Scholarship",
        "provider": "Colgate-Palmolive India",
        "level": "UG",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": None,
        "min_percentage": None,
        "benefit_amount": "Up to Rs. 50,000 per year",
        "description": "A merit-based scholarship for undergraduate students across streams, awarded based on academic performance and an essay-based application.",
        "tags": "Colgate merit undergraduate essay",
        "url": "https://www.buddy4study.com",
    },

    # ---------------- STUDY ABROAD / MS & PhD FUNDING ----------------
    {
        "name": "Fulbright-Nehru Master's Fellowship",
        "provider": "United States-India Educational Foundation (USIEF)",
        "level": "Study Abroad (Masters, USA)",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": None,
        "min_percentage": None,
        "benefit_amount": "Full tuition, living stipend, airfare for a Master's programme in the USA",
        "description": "A fully funded fellowship for Indian students to pursue a one- or two-year Master's degree at a US university in fields including engineering, public health, and social sciences.",
        "tags": "USA masters fully funded fellowship USIEF study abroad",
        "url": "https://www.usief.org.in",
    },
    {
        "name": "Inlaks Shivdasani Scholarship",
        "provider": "Inlaks Shivdasani Foundation",
        "level": "Study Abroad (Masters/PhD)",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": None,
        "min_percentage": None,
        "benefit_amount": "Up to USD 100,000 covering tuition and living costs",
        "description": "One of the largest privately funded scholarships for Indian students admitted to top-ranked graduate programmes in the US, UK, and Europe across most disciplines.",
        "tags": "study abroad USA UK Europe masters PhD private funded",
        "url": "https://www.inlaksfoundation.org",
    },
    {
        "name": "JN Tata Endowment for Higher Education",
        "provider": "Tata Trusts",
        "level": "Study Abroad (Masters/PhD)",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": None,
        "min_percentage": None,
        "benefit_amount": "Interest-free loan-scholarship, typically Rs. 1-10 lakh",
        "description": "A century-old loan-scholarship scheme supporting Indian students admitted to postgraduate programmes abroad, disbursed as a partially returnable interest-free loan.",
        "tags": "Tata study abroad loan scholarship masters PhD",
        "url": "https://www.jntataendowment.org",
    },
    {
        "name": "KC Mahindra Scholarship for Post-Graduate Studies Abroad",
        "provider": "KC Mahindra Education Trust",
        "level": "Study Abroad (Masters)",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": None,
        "min_percentage": None,
        "benefit_amount": "Interest-free loan up to Rs. 8,00,000",
        "description": "Offers interest-free loan-scholarships to meritorious Indian students who have secured admission to a recognised postgraduate programme overseas.",
        "tags": "Mahindra study abroad masters loan scholarship",
        "url": "https://www.kcmet.org",
    },
    {
        "name": "Chevening Scholarship",
        "provider": "UK Foreign, Commonwealth & Development Office",
        "level": "Study Abroad (Masters, UK)",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": None,
        "min_percentage": None,
        "benefit_amount": "Full tuition, living stipend, and travel costs for a one-year UK Master's",
        "description": "The UK government's global scholarship programme funding future leaders to pursue a one-year Master's degree at any UK university, with a strong alumni network.",
        "tags": "UK masters fully funded government scholarship leadership",
        "url": "https://www.chevening.org",
    },
    {
        "name": "Commonwealth Scholarship for Indian Students",
        "provider": "Commonwealth Scholarship Commission, UK",
        "level": "Study Abroad (Masters/PhD, UK)",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": None,
        "min_percentage": None,
        "benefit_amount": "Full tuition, living allowance, and airfare",
        "description": "Funds Master's and PhD study at UK universities for students from Commonwealth countries in subjects linked to development priorities.",
        "tags": "UK commonwealth masters PhD fully funded development",
        "url": "https://cscuk.fcdo.gov.uk",
    },
    {
        "name": "DAAD Scholarship for Indian Students (Germany)",
        "provider": "German Academic Exchange Service",
        "level": "Study Abroad (Masters/PhD, Germany)",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": None,
        "min_percentage": None,
        "benefit_amount": "Monthly stipend, health insurance, and travel allowance",
        "description": "Supports Indian graduates pursuing Master's or doctoral study at German universities, particularly in engineering, natural sciences, and development-related fields.",
        "tags": "Germany DAAD masters PhD engineering sciences funded",
        "url": "https://www.daad.in",
    },

    # ---------------- OPEN / ANY-CATEGORY, MISC ----------------
    {
        "name": "National Talent Search Examination (NTSE) Scholarship",
        "provider": "NCERT",
        "level": "School (Class 11-12) to UG/PG",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": None,
        "min_percentage": None,
        "benefit_amount": "Rs. 1,250 - 2,000 per month",
        "description": "Identifies and nurtures talented students through a state and national level test in Class 10, providing a scholarship that continues through postgraduate study.",
        "tags": "NTSE talent search merit exam NCERT long term",
        "url": "https://ncert.nic.in/national-talent-examination.php",
    },
    {
        "name": "Prime Minister's Scholarship Scheme for Central Armed Police Forces Wards",
        "provider": "Ministry of Home Affairs",
        "level": "UG/Professional",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": None,
        "min_percentage": 60,
        "benefit_amount": "Rs. 2,500 - 3,000 per month",
        "description": "Supports the wards and widows of Central Armed Police Force and Assam Rifles personnel pursuing professional and technical degree courses.",
        "tags": "CAPF defence wards professional technical PM scholarship",
        "url": "https://scholarships.gov.in",
    },
    {
        "name": "Central Sector Scheme for Single Girl Child (CBSE)",
        "provider": "CBSE",
        "level": "School (Class 11-12)",
        "category": "General",
        "gender": "Female",
        "state": "All India",
        "max_income": None,
        "min_percentage": 60,
        "benefit_amount": "Rs. 500 per month",
        "description": "Provides a monthly scholarship to the only girl child in a family who scored well in Class 10 and continues into Class 11 and 12.",
        "tags": "single girl child CBSE school scholarship",
        "url": "https://cbse.gov.in",
    },
    {
        "name": "Swanath Scholarship for Orphan Students",
        "provider": "Buddy4Study / Corporate CSR pool",
        "level": "School/UG",
        "category": "EWS",
        "gender": "Any",
        "state": "All India",
        "max_income": None,
        "min_percentage": None,
        "benefit_amount": "Course-fee based support",
        "description": "Aimed at orphaned students, including those who lost parents to COVID-19, to continue their school or undergraduate education without financial interruption.",
        "tags": "orphan students COVID fee support vulnerable",
        "url": "https://www.buddy4study.com",
    },
    {
        "name": "Google Generation Scholarship (India)",
        "provider": "Google",
        "level": "UG (Computer Science)",
        "category": "General",
        "gender": "Any",
        "state": "All India",
        "max_income": None,
        "min_percentage": None,
        "benefit_amount": "Course-fee support plus mentorship and Google conference invite",
        "description": "Supports undergraduate computer science students, with an emphasis on underrepresented groups in tech, through financial aid and mentorship from Google engineers.",
        "tags": "Google computer science tech underrepresented mentorship",
        "url": "https://buildyourfuture.withgoogle.com/scholarships",
    },
    {
        "name": "Central Sector Interest Subsidy Scheme (Education Loan)",
        "provider": "Ministry of Education",
        "level": "UG/PG (any recognised course)",
        "category": "EWS",
        "gender": "Any",
        "state": "All India",
        "max_income": 450000,
        "min_percentage": None,
        "benefit_amount": "Full interest subsidy during the moratorium period on education loans",
        "description": "Not a scholarship but a loan-interest subsidy for economically weaker students taking an education loan under the Indian Banks' Association model loan scheme.",
        "tags": "education loan interest subsidy EWS bank loan",
        "url": "https://vidyalakshmi.co.in",
    },
]
